#!/bin/bash
#PBS -N ARK_CO2CH4N2_screen
#PBS -o ARK_CO2CH4N2_screen.out
#PBS -e ARK_CO2CH4N2_screen.err
#PBS -l nodes=1:ppn=1
#PBS -l walltime=96:00:00
#PBS -q shared

cd $PBS_O_WORKDIR
export RASPA_DIR="/home/cwilmer/ark111/RASPA-2.0-CF"

	START_FILE=$INITIAL
	NUM_FILES=$TOTAL
	#FILE_NAME=$NAME
	#FILE_LIST=$FILELIST

	cp co2sim $SCRATCH/co2sim
	cp ch4sim $SCRATCH/ch4sim
	cp n2sim $SCRATCH/n2sim

	cd $SCRATCH

	for ((i = START_FILE; i < NUM_FILES + START_FILE; i++))
	do
		MAT_NAME="MAT-$i"
	
		#copy forcefield data
		cp /home/cwilmer/ark111/RASPA-2.0-CF/forcefield/$MAT_NAME/* $SCRATCH

	#co2 simulation	
		sed -i "s/^Forcefield.*/Forcefield                    $MAT_NAME/" $SCRATCH/co2sim
		sed -i "s/^FrameworkName.*/FrameworkName $MAT_NAME/" $SCRATCH/co2sim
		$RASPA_DIR/src/simulate -i co2sim

	#co2 data
	#excess
		#cm3/gr
		VALUE=$(cat $SCRATCH/Output/System_0/output* | grep "Average loading excess.*(STP)/gr" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> co2_exc_cc_gr.txt
		#cm3/cm3
		VALUE=$(cat $SCRATCH/Output/System_0/output* | grep "Average loading excess.*(STP)/cm" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> co2_exc_cc_cc.txt
		#mol/kg
		VALUE=$(cat $SCRATCH/Output/System_0/output* | grep "Average loading excess.*mol.*kg" | awk '{print $6"\t"$8}')
		echo $MAT_NAME"   "$VALUE >> co2_exc_mol_kg.txt
	#absolute
		#cm3/gr
		VALUE=$(cat ./Output/System_0/output* | grep "Average loading abs.*(STP)/gr" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> co2_abs_cc_gr.txt
		#cm3/cm3
		VALUE=$(cat ./Output/System_0/output* | grep "Average loading abs.*(STP)/cm" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> co2_abs_cc_cc.txt
		#mol/kg
		VALUE=$(cat ./Output/System_0/output* | grep "Average loading abs.*mol.*kg" | awk '{print $6"\t"$8}')
		echo $MAT_NAME"   "$VALUE >> co2_abs_mol_kg.txt
	#system data
		VALUE=$(cat $SCRATCH/Output/System_0/output_"$MAT_NAME"_* | grep desorption: -A 9 | grep KJ/MOL | awk '{print $1"\t"$3}')
		echo $MAT_NAME"   "$VALUE >> co2_heatDesorpTotal.txt
		VALUE=$(cat $SCRATCH/Output/System_0/output_"$MAT_NAME"_* | grep desor.*Host-Adsorbate -A 9 | grep KJ/MOL | awk '{print $1"\t"$3}')
		echo $MAT_NAME"   "$VALUE >> co2_heatDesorpHostAds.txt
		VALUE=$(cat $SCRATCH/Output/System_0/output_"$MAT_NAME"_* | grep desor.*Ads.*-Ads -A 9 | grep KJ/MOL | awk '{print $1"\t"$3}')
		echo $MAT_NAME"   "$VALUE >> co2_heatDesorpAdsAds.txt

		#ch4 simulation
	
		sed -i "s/^Forcefield.*/Forcefield                    $MAT_NAME/" $SCRATCH/ch4sim
		sed -i "s/^FrameworkName.*/FrameworkName $MAT_NAME/" $SCRATCH/ch4sim
		$RASPA_DIR/src/simulate -i $SCRATCH/ch4sim

	#h4 data
	#excess
		#cm3/gr
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading excess.*(STP)/gr" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> ch4_exc_cc_gr.txt
		#cm3/cm3
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading excess.*(STP)/cm" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> ch4_exc_cc_cc.txt
		#mol/kg
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading excess.*mol.*kg" | awk '{print $6"\t"$8}')
		echo $MAT_NAME"   "$VALUE >> ch4_exc_mol_kg.txt
	#absolute
		#cm3/gr
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading abs.*(STP)/gr" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> ch4_abs_cc_gr.txt
		#cm3/cm3
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading abs.*(STP)/cm" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> ch4_abs_cc_cc.txt
		#mol/kg
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading abs.*mol.*kg" | awk '{print $6"\t"$8}')
		echo $MAT_NAME"   "$VALUE >> ch4_abs_mol_kg.txt
	#system data
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep desorption: -A 9 | grep KJ/MOL | awk '{print $1"\t"$3}')
		echo $MAT_NAME"   "$VALUE >> ch4_heatDesorpTotal.txt
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep desor.*Host-Adsorbate -A 9 | grep KJ/MOL | awk '{print $1"\t"$3}')
		echo $MAT_NAME"   "$VALUE >> ch4_heatDesorpHostAds.txt
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep desor.*Ads.*-Ads -A 9 | grep KJ/MOL | awk '{print $1"\t"$3}')
		echo $MAT_NAME"   "$VALUE >> ch4_heatDesorpAdsAds.txt

	#n2 simulation	
		sed -i "s/^Forcefield.*/Forcefield                    $MAT_NAME/" $SCRATCH/n2sim
		sed -i "s/^FrameworkName.*/FrameworkName $MAT_NAME/" $SCRATCH/n2sim
		$RASPA_DIR/src/simulate -i $SCRATCH/n2sim

	#n2 data
	#excess
		#cm3/gr
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading excess.*(STP)/gr" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> n2_exc_cc_gr.txt
		#cm3/cm3
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading excess.*(STP)/cm" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> n2_exc_cc_cc.txt
		#mol/kg
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading excess.*mol.*kg" | awk '{print $6"\t"$8}')
		echo $MAT_NAME"   "$VALUE >> n2_exc_mol_kg.txt
	#absolute
		#cm3/gr
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading abs.*(STP)/gr" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> n2_abs_cc_gr.txt
		#cm3/cm3
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading abs.*(STP)/cm" | awk '{print $7"\t"$9}')
		echo $MAT_NAME"   "$VALUE >> n2_abs_cc_cc.txt
		#mol/kg
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep "Average loading abs.*mol.*kg" | awk '{print $6"\t"$8}')
		echo $MAT_NAME"   "$VALUE >> n2_abs_mol_kg.txt
	#system data
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep desorption: -A 9 | grep KJ/MOL | awk '{print $1"\t"$3}')
		echo $MAT_NAME"   "$VALUE >> n2_heatDesorpTotal.txt
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep desor.*Host-Adsorbate -A 9 | grep KJ/MOL | awk '{print $1"\t"$3}')
		echo $MAT_NAME"   "$VALUE >> n2_heatDesorpHostAds.txt
		VALUE=$(cat ./Output/System_0/output_"$MAT_NAME"_* | grep desor.*Ads.*-Ads -A 9 | grep KJ/MOL | awk '{print $1"\t"$3}')
		echo $MAT_NAME"   "$VALUE >> n2_heatDesorpAdsAds.txt

	rm -rf DLPOLY Movies Output Restart Tinker VTK
	rm *.def

	mkdir data_MAT-$INITIAL.thru.$TOTAL
	cp *.txt ./data_MAT-$INITIAL.thru.$TOTAL
	cp -rf data_MAT-$INITIAL.thru.$TOTAL ~/projects/

	done
